######################################
# Root CD 
######################################
#- CD_0_0 :
#  - label : Root
#    interval : 1
#    errortype : 0xF
######################################
# Root CD and Level 1 CD
######################################
#- CD_0_0 :
#  - label : Root
#    interval : 1
#    errortype : 0xF
#  - CD_1_1 :
#    - label : main_loop
#      interval : 1
#      errortype : 0xE
######################################
# Root CD, Level 1 and  Level2 CD
######################################
#- CD_0_0 :
#  - label    : Root
#    interval : 1
#    errortype: 0xF
#  - CD_1_1 :
#    - label    : main_loop
#      interval : 1
#      errortype: 0xE
#    - CD_2_2 :
#      - label    : advanceVelocity_start
#        interval : 1
#        errortype: 0xE
#    - CD_2_3 :
#      - label    : advancePosition
#        interval : 1
#        errortype: 0xE
#    - CD_2_4 :
#      - label    : redistributeAtoms
#        interval : 1
#        errortype: 0xE
#    - CD_2_5 :
#      - label    : computeForce
#        interval : 1
#        errortype: 0xE
#    - CD_2_6 :
#      - label    : advanceVelocity_end
#        interval : 1
#        errortype: 0xE
######################################
# Root, Level1, Level2, and Level3
######################################
#- CD_0_0 :
#  - label    : Root
#    interval : 1
#    errortype: 0xE
#  - CD_1_1 :
#    - label    : main_loop
#      interval : 1
#      errortype: 0xE
#    - CD_2_2 :
#      - label    : advanceVelocity_start
#        interval : 1
#        errortype: 0xE
#    - CD_2_3 :
#      - label    : advancePosition
#        interval : 1
#        errortype: 0xE
#    - CD_2_4 :
#      - label    : redistributeAtoms
#        interval : 1
#        errortype: 0xE
#    - CD_2_5 :
#      - label    : computeForce
#        interval : 1
#        errortype: 0xE
#      - CD_3_6 :
#        - label    : ljForce_in_timestep
#          interval : 1
#          errortype: 0xC
#    - CD_2_8 :
#      - label    : advanceVelocity_end
#        interval : 1
#        errortype: 0xE
######################################
# Root, Level1, Level2, Level3, Level4
######################################
- CD_0_0 :
  - label    : Root
    interval : 1
    errortype: 0xE
  - CD_1_1 :
    - label    : main_loop
      interval : 1
      errortype: 0xE
    - CD_2_2 :
      - label    : advanceVelocity_start
        interval : 1
        errortype: 0xE
    - CD_2_3 :
      - label    : advancePosition
        interval : 1
        errortype: 0xE
    - CD_2_4 :
      - label    : redistributeAtoms
        interval : 1
        errortype: 0xE
    - CD_2_5 :
      - label    : computeForce
        interval : 1
        errortype: 0xE
      - CD_3_6 :
        - label    : ljForce_in_timestep
          interval : 1
          errortype: 0xC
        - CD_4_7 :
          - label    : ljForce_outmost_loop
            interval : 1
            errortype: 0xC
    - CD_2_8 :
      - label    : advanceVelocity_end
        interval : 1
        errortype: 0xE
######################################
# Root:   0xF and KHDD
# Level1: 0xF and kDRAM
# Level2: 0xC and kDRAM
######################################
- FAILURE :
  - F1 : 0.000
  - F2 : 0.000
  - F4 : 0.00 
#  - F8 : 0.00
#  - F8 : 0.005
#  - F8 : 0.01
  - F8 : 0.02
#  - F8 : 0.04
