# - CD_0_0 :
#   - label : 0_Root
#     interval : 1
#     errortype : 0xF
#   - CD_1_1 :
#     - label : advanceVelocity_start
#       interval : 1
#       errortype : 0xF
#   - CD_1_2 :
#     - label : advancePosition
#       interval : 1
#       errortype : 0xF
#   - CD_1_3 :
#     - label : redistributeAtoms
#       interval : 1
#       errortype : 0xF
#   - CD_1_4 :
#     - label : computeForce
#       interval : 1
#       errortype : 0xF
#   - CD_1_5 :
#     - label : advanceVelocity_end
#       interval : 1
#       errortype : 0xF
# - CD_0_0 :
#   - label : 0_Root
#     interval : 1
#     errortype : 0xF
#   - CD_1_1 :
#     - label : advanceVelocity_start
#       interval : 1
#       errortype : 0xF
#   - CD_1_2 :
#     - label : advancePosition
#       interval : 1
#       errortype : 0xF
#   - CD_1_3 :
#     - label : redistributeAtoms
#       interval : 1
#       errortype : 0xF
#   - CD_1_4 :
#     - label : computeForce
#       interval : 1
#       errortype : 0xF
#   - CD_1_5 :
#     - label : advanceVelocity_end
#       interval : 1
#       errortype : 0xF
- CD_0_0 :
  - label : Root
    interval : 1
    errortype : 0xF
  - CD_1_1 :
    - label : advanceVelocity_start
      interval : 1
      errortype : 0x7
  - CD_1_2 :
    - label : advancePosition
      interval : 1
      errortype : 0x7
  - CD_1_3 :
    - label : redistributeAtoms
      interval : 1
      errortype : 0x7
    - CD_2_4 :
      - label : computeForce
        interval : 1
        errortype : 0x3
      - CD_3_5 :
        - label : ljForce_innermost
          interval : 1
          errortype : 0x1
    - CD_2_6 :
      - label : advanceVelocity_end
        interval : 1
        errortype : 0x7
#- FAILURE :
#  - F1 : 0.001
#  - F2 : 0.005
#  - F4 : 0.08
#  - F8 : 0.01
- FAILURE :
  - F1 : 0.000
  - F2 : 0.000
  - F4 : 0.00
  - F8 : 0.00
